### ISSUE TITLE
discord_channel is set to None at this point in execution.

### ISSUE THREAD

**Issue by shiftybit** [seanicus64/BridgeDiscord#2]
https://github.com/seanicus64/BridgeDiscord/blob/1715a212e0eac88c6b14c9b680b3d9a51f495795/disc.py#L33
discord_channel is, at least in my configuration, still None and when I try to get a message relayed, it will crash. 
 
Task exception was never retrieved
future: <Task finished coro=<my_background_task() done, defined at disc.py:22> exception=InvalidArgument('Destination must be Channel, PrivateChannel, User, or Object. Received NoneType',)>
Traceback (most recent call last):
  File "disc.py", line 35, in my_background_task
    await client.send_message(discord_channel, "**<{}>**: {}".format(m.user, m.message))
  File "/home/darkscrypt/.local/lib/python3.6/site-packages/discord/client.py", line 1145, in send_message
    channel_id, guild_id = yield from self._resolve_destination(destination)
  File "/home/darkscrypt/.local/lib/python3.6/site-packages/discord/client.py", line 289, in _resolve_destination
    raise InvalidArgument(fmt.format(destination))
discord.errors.InvalidArgument: Destination must be Channel, PrivateChannel, User, or Object. Received NoneType

To Replicate: 
Links: 
[links top]
#general = #general
#top = #top
#topdev = #topdev

Type in one of the servers, so long as the message actually gets past previous glitch (i used pdb to override the condition and force it to send even though 	if  not channel_link_id was tripping for my channels. (on account of it being channel id 0, which would evaluate true in this condition)

When the message comes through into disc.py, a fatal exception will occur at this line (35). The loop above this line, that attempts to determine the discord channel is failing here, likely due to the formatting and # signs of the links section, or a difference in ascii / vs unicode, or non displaying characters, or something of that nature. In other words, the strings do not line up, and we end up not having a correlated discord channel to send the message through. 

After this exception occurrs, disc.py will need to be restarted in order to trip the event again.

**Comment by seanicus64** [comment]
The left side refers to the "alien" channel name, and the right to IRC, so the value on the right should usually begin with a "#".  The one on the left is entirely dependent on the alien service's system.  Discord seems to use #, but actual channel names do not begin with #.  So it should be
    general = #general
    top = #top
    topdev = #topdev
Will change documentation to reflect this.
